### ISSUE TITLE
リリースタグ

### ISSUE THREAD

**Issue by shiena** [ina-amagami/unity-reference-viewer#11]
OpenUPMに追加したのですがタグがないとUnityのPackage Managerから利用できませんでした。
https://openupm.com/packages/jp.amagamina.reference-viewer/

差し支えなければpackage.jsonと同じ`1.0.0`タグをつけていただけないでしょうか？

**Comment by ina-amagami** [comment]
ご対応ありがとうございます！タグを付けてOpenUPM経由でインストールできることを確認しました。

**Comment by shiena** [comment]
ありがとうございます。こちらもOpenUPM経由でインストールできましたのでクローズします。
